wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.31
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.6
batch_size:
  desc: null
  value: 128
epochs:
  desc: null
  value: 20
final_activation:
  desc: null
  value: softmax
learning_rate:
  desc: null
  value: 0.01
optimizer:
  desc: null
  value: adam
prefinal_activation:
  desc: null
  value: relu
seed:
  desc: null
  value: 42
